### ISSUE TITLE
podman-compose fails to parse docker-compose.prod.yml with AttributeError

### ISSUE THREAD

**Issue by mikesvoboda** [mikesvoboda/nemotron-v3-home-security-intelligence#1921]
## Problem

`podman-compose` fails when trying to build AI services from `docker-compose.prod.yml` with the following error:

```
File "/usr/lib/python3.14/site-packages/podman_compose.py", line 341, in norm_as_dict
    dst = [i.split("=", 1) for i in src if i]
           ^^^^^^^
AttributeError: 'dict' object has no attribute 'split'
```

## Environment

* Fedora with Python 3.14
* podman-compose from system packages
* docker-compose.prod.yml with `deploy.resources.reservations.devices` for GPU

## Root Cause

The `norm_as_dict` function in podman-compose expects environment variables as strings but encounters a dict structure (likely from the `deploy` section GPU device reservations).

## Reproduction

```bash
./scripts/redeploy.sh
# or directly:
podman-compose -f docker-compose.prod.yml build ai-detector
```

## Workarounds

1. Use `docker compose` instead (works correctly)
2. Build AI images separately with `podman build`

## Potential Fixes

1. Update podman-compose to latest version
2. Restructure compose file to avoid the parsing issue
3. Use docker compose for hybrid deployments
4. File upstream bug with podman-compose project

## Related

* Works correctly with Docker Compose v2.40.3
* Affects: `scripts/redeploy.sh` hybrid mode
